# Generated by Django 4.0.5 on 2022-07-30 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='report_total',
        ),
        migrations.RemoveField(
            model_name='post',
            name='report_value',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vote_value',
        ),
    ]
