# Generated by Django 4.0.5 on 2022-07-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_comment_com_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='report_value',
            field=models.IntegerField(choices=[('up', 'Reported'), ('down', 'Report')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='vote_value',
            field=models.IntegerField(choices=[('up', 'UP VOTE'), ('down', 'DOWN VOTE')], default=0),
        ),
    ]
