# Generated by Django 4.0.5 on 2022-07-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_alter_comment_report_value_alter_comment_vote_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='com_image',
        ),
        migrations.AlterField(
            model_name='comment',
            name='vote_value',
            field=models.IntegerField(choices=[('up', 'UP VOTE'), ('up', 'DOWN VOTE')], default='up'),
        ),
        migrations.AlterField(
            model_name='post',
            name='vote_value',
            field=models.IntegerField(choices=[('up', 'UP VOTE'), ('down', 'DOWN VOTE')], default='up'),
        ),
    ]
