# Generated by Django 4.0.5 on 2022-07-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_comment_report_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-vote_Ratio', '-vote_total', 'title']},
        ),
    ]
